#!/usr/bin/env python3
"""
run_pipeline.py — End-to-end orchestrator for the off-target liability workflow.

Chains the analysis stages: resolve -> panel -> ADMET -> similarity -> DeepPurpose ->
ground truth -> benchmark -> consolidate -> figures, leaving <dir>/data/report_data.json
and <dir>/figures/* ready for the report.

The report is the REQUIRED terminal step of the workflow, but it is NOT built here: it is
generated by the agent through the `pdf-report-generation` skill (with the infographic from the
GenerateImage tool), so report styling stays consistent across the suite. See SKILL.md step 8.

This is a convenience driver; each stage can also be run standalone (see SKILL.md).

Usage:
  python run_pipeline.py --query "<name|SMILES|InChIKey|CHEMBLxxxx>" --outdir <dir> \
        [--adaptive] [--admet-engine auto|admet_ai|biomni]
"""
import argparse, os, sys, json, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)


def run(cmd, label):
    print(f"\n=== {label} ===", flush=True)
    r = subprocess.run(cmd, capture_output=True, text=True)
    out = (r.stdout or "").strip().splitlines()
    last = out[-1] if out else ""
    if r.returncode != 0:
        print(f"[FAIL] {label} (exit {r.returncode})")
        print((r.stderr or "")[-800:])
        return None
    print(last[:400])
    try:
        return json.loads(last)
    except Exception:
        return {"_raw": last}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--query", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--adaptive", action="store_true")
    ap.add_argument("--admet-engine", default="auto")
    ap.add_argument("--min-actives", type=int, default=5)
    args = ap.parse_args()
    O = args.outdir
    os.makedirs(f"{O}/data", exist_ok=True)
    S = lambda name: os.path.join(HERE, name)

    # 1. resolve
    r = subprocess.run([sys.executable, S("resolve_compound.py"),
                        "--query", args.query, "--outdir", O],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print("[FAIL] resolve\n", r.stderr[-800:]); sys.exit(1)
    comp = json.loads(r.stdout.strip().splitlines()[-1])
    json.dump(comp, open(f"{O}/compound.json", "w"), indent=2)
    print(f"=== resolve ===\n{comp['name']} | {comp['chembl_id']} | MW {comp['MW']}")
    smi, ik14 = comp["smiles"], comp["inchikey14"]

    # 2. panel (compound.json supplies the intended primary target for on/off-target separation)
    panel_cmd = [sys.executable, S("build_panel.py"), "--smiles", smi,
                 "--inchikey14", ik14, "--core", f"{PKG}/references/core_panel.csv",
                 "--outdir", O, "--compound-json", f"{O}/compound.json"]
    if args.adaptive:
        panel_cmd.append("--adaptive")
    run(panel_cmd, "panel")

    # 3. ADMET
    run([sys.executable, S("run_admet.py"), "--smiles", smi, "--outdir", O,
         "--engine", args.admet_engine], "ADMET")

    # 4. similarity
    run([sys.executable, S("predict_similarity.py"), "--smiles", smi,
         "--inchikey14", ik14, "--panel", f"{O}/data/prediction_panel.csv",
         "--outdir", O, "--min-actives", str(args.min_actives)], "similarity")

    # 5. DeepPurpose
    run([sys.executable, S("run_deeppurpose.py"), "--smiles", smi,
         "--panel-seqs", f"{O}/tmp/panel_with_seqs.csv", "--outdir", O], "DeepPurpose")

    # 6. ground truth
    run([sys.executable, S("fetch_ground_truth.py"), "--chembl-id",
         comp["chembl_id"], "--outdir", O,
         "--compound-json", f"{O}/compound.json"], "ground truth")

    # 7. benchmark (primary target excluded from the off-target benchmark)
    run([sys.executable, S("benchmark.py"),
         "--sim", f"{O}/data/offtarget_similarity_predictions.csv",
         "--dp", f"{O}/data/offtarget_deeppurpose_predictions.csv",
         "--truth", f"{O}/data/known_targets_collapsed.csv", "--outdir", O,
         "--compound-json", f"{O}/compound.json"], "benchmark")

    # 8. consolidate
    run([sys.executable, S("consolidate.py"), "--outdir", O,
         "--compound-json", f"{O}/compound.json",
         "--references", f"{PKG}/references/references.json"], "consolidate")

    # 9. figures
    run([sys.executable, S("make_figures.py"), "--outdir", O,
         "--compound", comp["name"], "--topn", "15"], "figures")

    # The stages above produced <dir>/data/report_data.json and <dir>/figures/*. The report itself
    # is the REQUIRED terminal step and is generated by the agent through the `pdf-report-generation`
    # skill (with the infographic from the GenerateImage tool) — it is not a subprocess here, so
    # report styling stays consistent across the suite.
    out_pdf = f"{O}/{comp['name'].lower()}_liability_report.pdf"
    print("\n=== analysis + figures complete ===")
    print(f"report_data: {O}/data/report_data.json")
    print(f"figures:     {O}/figures/")
    print("Next (REQUIRED terminal step): generate the infographic with the GenerateImage tool")
    print(f"  -> {O}/figures/infographic.png, then build the PDF via the pdf-report-generation")
    print(f"  skill from report_data.json + figures -> {out_pdf}")


if __name__ == "__main__":
    main()
